//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueCardPortal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlueCardPortal.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Декларация за достъпност - ППИР.
        /// </summary>
        public static string AccessabilityDeclaration {
            get {
                return ResourceManager.GetString("AccessabilityDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Политика за достъпност.
        /// </summary>
        public static string AccessabilityPolicy {
            get {
                return ResourceManager.GetString("AccessabilityPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нов адрес.
        /// </summary>
        public static string AddAddress {
            get {
                return ResourceManager.GetString("AddAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подаване на ново заявление.
        /// </summary>
        public static string AddApplication {
            get {
                return ResourceManager.GetString("AddApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нов контакт.
        /// </summary>
        public static string AddContact {
            get {
                return ResourceManager.GetString("AddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави данни за чужденец.
        /// </summary>
        public static string AddForeignerSmall {
            get {
                return ResourceManager.GetString("AddForeignerSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нов документ.
        /// </summary>
        public static string AddPersonIdDocument {
            get {
                return ResourceManager.GetString("AddPersonIdDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съвпада с адреса на седалището на работодателя.
        /// </summary>
        public static string AddressIsSame {
            get {
                return ResourceManager.GetString("AddressIsSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес на месторабота.
        /// </summary>
        public static string AddressIsSameTitle {
            get {
                return ResourceManager.GetString("AddressIsSameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид адрес.
        /// </summary>
        public static string AddressKind {
            get {
                return ResourceManager.GetString("AddressKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Място на работа - обект.
        /// </summary>
        public static string AddressObject {
            get {
                return ResourceManager.GetString("AddressObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Апартамент.
        /// </summary>
        public static string Apartment {
            get {
                return ResourceManager.GetString("Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съвпада с адреса на седалището.
        /// </summary>
        public static string AplicantEmployerContactAddressIsSame {
            get {
                return ResourceManager.GetString("AplicantEmployerContactAddressIsSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съвпада с адреса за контакт на работодателя.
        /// </summary>
        public static string ApplicantContactAddressIsSame {
            get {
                return ResourceManager.GetString("ApplicantContactAddressIsSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕГН на заявителя.
        /// </summary>
        public static string ApplicantEgn {
            get {
                return ResourceManager.GetString("ApplicantEgn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име на заявителя.
        /// </summary>
        public static string ApplicantName {
            get {
                return ResourceManager.GetString("ApplicantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес за кореспонденция на заявител.
        /// </summary>
        public static string ApplicantPersonAddress {
            get {
                return ResourceManager.GetString("ApplicantPersonAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роля на заявителя.
        /// </summary>
        public static string ApplicantRole {
            get {
                return ResourceManager.GetString("ApplicantRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Физическо лице.
        /// </summary>
        public static string ApplicantRole1 {
            get {
                return ResourceManager.GetString("ApplicantRole1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Служител на юридическо лице.
        /// </summary>
        public static string ApplicantRole2 {
            get {
                return ResourceManager.GetString("ApplicantRole2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид заявител.
        /// </summary>
        public static string ApplicantType {
            get {
                return ResourceManager.GetString("ApplicantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид идентификатор.
        /// </summary>
        public static string ApplicantUicType {
            get {
                return ResourceManager.GetString("ApplicantUicType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допълнителна информация, свързана със заявлението.
        /// </summary>
        public static string ApplicationAdditionalInfo {
            get {
                return ResourceManager.GetString("ApplicationAdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявление № {0}.
        /// </summary>
        public static string ApplicationApplyNumber {
            get {
                return ResourceManager.GetString("ApplicationApplyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продължете попълването на незавършените Ви чернови на заявления.
        /// </summary>
        public static string ApplicationDraftList {
            get {
                return ResourceManager.GetString("ApplicationDraftList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неподадени Заявления.
        /// </summary>
        public static string ApplicationDraftListTitle {
            get {
                return ResourceManager.GetString("ApplicationDraftListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От дата.
        /// </summary>
        public static string ApplicationFilterFromDate {
            get {
                return ResourceManager.GetString("ApplicationFilterFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to до дата.
        /// </summary>
        public static string ApplicationFilterToDate {
            get {
                return ResourceManager.GetString("ApplicationFilterToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер на заявление.
        /// </summary>
        public static string ApplicationNumber {
            get {
                return ResourceManager.GetString("ApplicationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявления.
        /// </summary>
        public static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Списък подадени заявления.
        /// </summary>
        public static string ApplicationSendList {
            get {
                return ResourceManager.GetString("ApplicationSendList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подаване на заявления.
        /// </summary>
        public static string ApplicationsText {
            get {
                return ResourceManager.GetString("ApplicationsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявление.
        /// </summary>
        public static string ApplicationType {
            get {
                return ResourceManager.GetString("ApplicationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Важно: Mоже да подавате само услуга Краткосрочна заетост до 90 дни - Приложение №5.
        /// </summary>
        public static string ApplicationTypeMessage {
            get {
                return ResourceManager.GetString("ApplicationTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прикачи.
        /// </summary>
        public static string Attach {
            get {
                return ResourceManager.GetString("Attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Към работния плот.
        /// </summary>
        public static string BackToWorkPlot {
            get {
                return ResourceManager.GetString("BackToWorkPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задължително да бъде попълнена следната комбинация : Улица и Номер ИЛИ Жилищен квартал и Сграда номер.
        /// </summary>
        public static string BCAddressErrorMessage {
            get {
                return ResourceManager.GetString("BCAddressErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете поне един адрес.
        /// </summary>
        public static string BCAddressListErrorMessage {
            get {
                return ResourceManager.GetString("BCAddressListErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете.
        /// </summary>
        public static string BCAttributeErrorMessage {
            get {
                return ResourceManager.GetString("BCAttributeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прикачете задължителните документи!.
        /// </summary>
        public static string BCDocumentsErrorMessage {
            get {
                return ResourceManager.GetString("BCDocumentsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете продължителност диапазона от {0} до {1} месеца.
        /// </summary>
        public static string BCEmploymentDurationMonthMessage {
            get {
                return ResourceManager.GetString("BCEmploymentDurationMonthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете валиден ЕГН.
        /// </summary>
        public static string BCIdentifierErrorMessageEGN {
            get {
                return ResourceManager.GetString("BCIdentifierErrorMessageEGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете валиден ЕИК.
        /// </summary>
        public static string BCIdentifierErrorMessageEIK {
            get {
                return ResourceManager.GetString("BCIdentifierErrorMessageEIK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете валиден ЛНЧ.
        /// </summary>
        public static string BCIdentifierErrorMessageLNCH {
            get {
                return ResourceManager.GetString("BCIdentifierErrorMessageLNCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете поне един личен документ на чужденеца.
        /// </summary>
        public static string BCPersonIdDocumentListErrorMessage {
            get {
                return ResourceManager.GetString("BCPersonIdDocumentListErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете валидна дата.
        /// </summary>
        public static string BCRangeDateErrorMessage {
            get {
                return ResourceManager.GetString("BCRangeDateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на раждане.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на раждане.
        /// </summary>
        public static string BirthDateFilter {
            get {
                return ResourceManager.GetString("BirthDateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to формат.
        /// </summary>
        public static string BirthDateTypeInput {
            get {
                return ResourceManager.GetString("BirthDateTypeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на раждане.
        /// </summary>
        public static string BirthMonth {
            get {
                return ResourceManager.GetString("BirthMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение №3а се използва за Синя Карта, ЕРПР, ВКТ и Сезонна заетост от 90 до 180 дни.
        /// </summary>
        public static string BlankPdf3a {
            get {
                return ResourceManager.GetString("BlankPdf3a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение №5 се използва за Краткосрочна заетост при сезонни работници до 90 дни.
        /// </summary>
        public static string BlankPdf5 {
            get {
                return ResourceManager.GetString("BlankPdf5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Образци на документи.
        /// </summary>
        public static string Blanks {
            get {
                return ResourceManager.GetString("Blanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сграда №.
        /// </summary>
        public static string BuildingNo {
            get {
                return ResourceManager.GetString("BuildingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтрий.
        /// </summary>
        public static string ButtonDeleteHint {
            get {
                return ResourceManager.GetString("ButtonDeleteHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попълването на заявлението ще бъде прекратено и въведените от Вас данни ще бъдат съхранени. Ще можете да продължите от мястото, до където сте стигнали!.
        /// </summary>
        public static string ButtonDraftHint {
            get {
                return ResourceManager.GetString("ButtonDraftHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Град.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете място на раждане на кирилица.
        /// </summary>
        public static string CityOfBirthRegularExpression {
            get {
                return ResourceManager.GetString("CityOfBirthRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Място на раждане.
        /// </summary>
        public static string CityОfBirth {
            get {
                return ResourceManager.GetString("CityОfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изчисти филтъра.
        /// </summary>
        public static string ClearFilter {
            get {
                return ResourceManager.GetString("ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Затвори.
        /// </summary>
        public static string CloseFilter {
            get {
                return ResourceManager.GetString("CloseFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жалба.
        /// </summary>
        public static string Complaint {
            get {
                return ResourceManager.GetString("Complaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От дата.
        /// </summary>
        public static string ComplaintFilterFromDate {
            get {
                return ResourceManager.GetString("ComplaintFilterFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to до дата.
        /// </summary>
        public static string ComplaintFilterToDate {
            get {
                return ResourceManager.GetString("ComplaintFilterToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обоснование.
        /// </summary>
        public static string ComplaintInfo {
            get {
                return ResourceManager.GetString("ComplaintInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жалба №.
        /// </summary>
        public static string ComplaintNumber {
            get {
                return ResourceManager.GetString("ComplaintNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жалби.
        /// </summary>
        public static string Complaints {
            get {
                return ResourceManager.GetString("Complaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Списък подадени жалби.
        /// </summary>
        public static string ComplaintSendList {
            get {
                return ResourceManager.GetString("ComplaintSendList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подаване на жалби по заявления.
        /// </summary>
        public static string ComplaintsText {
            get {
                return ResourceManager.GetString("ComplaintsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърждение.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съвпада с адреса на седалището на работодателя.
        /// </summary>
        public static string ContactAddressIsSame {
            get {
                return ResourceManager.GetString("ContactAddressIsSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакт.
        /// </summary>
        public static string ContactDescription {
            get {
                return ResourceManager.GetString("ContactDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете информация за контакт.
        /// </summary>
        public static string ContactListErrorMessage {
            get {
                return ResourceManager.GetString("ContactListErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете предпочитан контакт.
        /// </summary>
        public static string ContactListPreferedErrorMessage {
            get {
                return ResourceManager.GetString("ContactListPreferedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данни за контакт.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string ContactType {
            get {
                return ResourceManager.GetString("ContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Държава.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Национална идентичност.
        /// </summary>
        public static string CountryFilter {
            get {
                return ResourceManager.GetString("CountryFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистически данни издадени по тип разрешения за чужденец.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика.
        /// </summary>
        public static string DashboardShort {
            get {
                return ResourceManager.GetString("DashboardShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Година.
        /// </summary>
        public static string DashboardYear {
            get {
                return ResourceManager.GetString("DashboardYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От година.
        /// </summary>
        public static string DashboardYearFrom {
            get {
                return ResourceManager.GetString("DashboardYearFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До година.
        /// </summary>
        public static string DashboardYearTo {
            get {
                return ResourceManager.GetString("DashboardYearTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печатна форма на заявление.
        /// </summary>
        public static string DocumentPrintForm {
            get {
                return ResourceManager.GetString("DocumentPrintForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявление_{0}.pdf.
        /// </summary>
        public static string DocumentPrintFormFileName {
            get {
                return ResourceManager.GetString("DocumentPrintFormFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string DocumentTitle {
            get {
                return ResourceManager.GetString("DocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип на документа.
        /// </summary>
        public static string DocumentType {
            get {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Други.
        /// </summary>
        public static string DocumentTypeOther {
            get {
                return ResourceManager.GetString("DocumentTypeOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начална дата.
        /// </summary>
        public static string DurationOfEmploymentFrom {
            get {
                return ResourceManager.GetString("DurationOfEmploymentFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продължителност (месеци).
        /// </summary>
        public static string DurationOfEmploymentMonth {
            get {
                return ResourceManager.GetString("DurationOfEmploymentMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Степен на образование.
        /// </summary>
        public static string EducationTypeVM {
            get {
                return ResourceManager.GetString("EducationTypeVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕГН.
        /// </summary>
        public static string EGN {
            get {
                return ResourceManager.GetString("EGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕИК.
        /// </summary>
        public static string EIK {
            get {
                return ResourceManager.GetString("EIK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронна поща.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брой служители.
        /// </summary>
        public static string EmployeeCount {
            get {
                return ResourceManager.GetString("EmployeeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брой чуждестранни служители не може да бъде по-голям от Брой служители.
        /// </summary>
        public static string EmployeeCountErrorMessage {
            get {
                return ResourceManager.GetString("EmployeeCountErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете {0}.
        /// </summary>
        public static string EmployeeRangeErrorMessage {
            get {
                return ResourceManager.GetString("EmployeeRangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес на работодателя.
        /// </summary>
        public static string EmployerAddresses {
            get {
                return ResourceManager.GetString("EmployerAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смяна на работодател.
        /// </summary>
        public static string EmployerChange {
            get {
                return ResourceManager.GetString("EmployerChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес за кореспонденция.
        /// </summary>
        public static string EmployerContactAddress {
            get {
                return ResourceManager.GetString("EmployerContactAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Седалище и адрес на управление.
        /// </summary>
        public static string EmployerHeadAddress {
            get {
                return ResourceManager.GetString("EmployerHeadAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployerHeadAddresses.
        /// </summary>
        public static string EmployerHeadAddresses {
            get {
                return ResourceManager.GetString("EmployerHeadAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕИК.
        /// </summary>
        public static string EmployerIdentifier {
            get {
                return ResourceManager.GetString("EmployerIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование на юридическото лице.
        /// </summary>
        public static string EmployerName {
            get {
                return ResourceManager.GetString("EmployerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длъжност.
        /// </summary>
        public static string EmploymentPosition {
            get {
                return ResourceManager.GetString("EmploymentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цел на наемане.
        /// </summary>
        public static string EmploymentReason {
            get {
                return ResourceManager.GetString("EmploymentReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продължаване на договор.
        /// </summary>
        public static string EmploymentType {
            get {
                return ResourceManager.GetString("EmploymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string Entrance {
            get {
                return ResourceManager.GetString("Entrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на влизане в страната.
        /// </summary>
        public static string EntryDate {
            get {
                return ResourceManager.GetString("EntryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Входна точка на влизане в страната.
        /// </summary>
        public static string EntryPoint {
            get {
                return ResourceManager.GetString("EntryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете валиден адрес на електронна поща.
        /// </summary>
        public static string ErrorEmailMessage {
            get {
                return ResourceManager.GetString("ErrorEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалиден файлов формат.
        /// </summary>
        public static string ErrorFileExt {
            get {
                return ResourceManager.GetString("ErrorFileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлът е с по-голям размер от допустимият.
        /// </summary>
        public static string ErrorFileMaxSIze {
            get {
                return ResourceManager.GetString("ErrorFileMaxSIze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изберете файл от локалното Ви устройство!.
        /// </summary>
        public static string ErrorNoFIle {
            get {
                return ResourceManager.GetString("ErrorNoFIle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете валиден телефон.
        /// </summary>
        public static string ErrorPhoneMessage {
            get {
                return ResourceManager.GetString("ErrorPhoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронни услуги.
        /// </summary>
        public static string EService {
            get {
                return ResourceManager.GetString("EService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на валидност.
        /// </summary>
        public static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предпочитан.
        /// </summary>
        public static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име на файл.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Етаж.
        /// </summary>
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брой чуждестранни служители.
        /// </summary>
        public static string ForeignEmployeeCount {
            get {
                return ResourceManager.GetString("ForeignEmployeeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настоящ адрес.
        /// </summary>
        public static string ForeignerAddress {
            get {
                return ResourceManager.GetString("ForeignerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес в Република България.
        /// </summary>
        public static string ForeignerAddresses {
            get {
                return ResourceManager.GetString("ForeignerAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЛНЧ на чуждестранното лице.
        /// </summary>
        public static string ForeignerFid {
            get {
                return ResourceManager.GetString("ForeignerFid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор на чужденец.
        /// </summary>
        public static string ForeignerIdentifier {
            get {
                return ResourceManager.GetString("ForeignerIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име на латиница.
        /// </summary>
        public static string ForeignerName {
            get {
                return ResourceManager.GetString("ForeignerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име на кирилица.
        /// </summary>
        public static string ForeignerNameCyrilic {
            get {
                return ResourceManager.GetString("ForeignerNameCyrilic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете име на кирилица.
        /// </summary>
        public static string ForeignerNameCyrilicRegularExpression {
            get {
                return ResourceManager.GetString("ForeignerNameCyrilicRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име чужденец.
        /// </summary>
        public static string ForeignerNameFilter {
            get {
                return ResourceManager.GetString("ForeignerNameFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете име на латиница.
        /// </summary>
        public static string ForeignerNameRegularExpression {
            get {
                return ResourceManager.GetString("ForeignerNameRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете поне един чужденец.
        /// </summary>
        public static string ForeignerSmallListErrorMessage {
            get {
                return ResourceManager.GetString("ForeignerSmallListErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пребивава ли лицето в България към момента.
        /// </summary>
        public static string ForeignerTypeIdentifier {
            get {
                return ResourceManager.GetString("ForeignerTypeIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка.
        /// </summary>
        public static string GetEmployer {
            get {
                return ResourceManager.GetString("GetEmployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подадена жалба.
        /// </summary>
        public static string HasActiveComplaint {
            get {
                return ResourceManager.GetString("HasActiveComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оригинал.
        /// </summary>
        public static string IsOriginal {
            get {
                return ResourceManager.GetString("IsOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на издаване.
        /// </summary>
        public static string IssueDate {
            get {
                return ResourceManager.GetString("IssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Издател.
        /// </summary>
        public static string IssuedBy {
            get {
                return ResourceManager.GetString("IssuedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правна форма.
        /// </summary>
        public static string LegalForm {
            get {
                return ResourceManager.GetString("LegalForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЛНЧ.
        /// </summary>
        public static string LNCH {
            get {
                return ResourceManager.GetString("LNCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЛНЧ.
        /// </summary>
        public static string LNCHFilter {
            get {
                return ResourceManager.GetString("LNCHFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход с еАвтентикация.
        /// </summary>
        public static string LoginMethod {
            get {
                return ResourceManager.GetString("LoginMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Методът за идентификация се предоставя от Министерството на електронното управление и може да изисква предварителна регистрация.
        /// </summary>
        public static string LoginMethodText {
            get {
                return ResourceManager.GetString("LoginMethodText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to разрешения за работа.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Семеен стаус.
        /// </summary>
        public static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гражданство.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НЕ.
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № на задгр. паспорт.
        /// </summary>
        public static string PassportNumber {
            get {
                return ResourceManager.GetString("PassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрешение.
        /// </summary>
        public static string PermitType {
            get {
                return ResourceManager.GetString("PermitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видове разрешения.
        /// </summary>
        public static string PermitTypeFilter {
            get {
                return ResourceManager.GetString("PermitTypeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер на документ.
        /// </summary>
        public static string PersonIdDocumentIdentifier {
            get {
                return ResourceManager.GetString("PersonIdDocumentIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документи за идентификация.
        /// </summary>
        public static string PersonIdDocuments {
            get {
                return ResourceManager.GetString("PersonIdDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серия.
        /// </summary>
        public static string PersonIdDocumentSeries {
            get {
                return ResourceManager.GetString("PersonIdDocumentSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип на документ.
        /// </summary>
        public static string PersonIdDocumentType {
            get {
                return ResourceManager.GetString("PersonIdDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документи за идентификация на чужденец.
        /// </summary>
        public static string PersonIdDocumentVM {
            get {
                return ResourceManager.GetString("PersonIdDocumentVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля въведете кирилица без следните символи запетайки,латиница,числа.
        /// </summary>
        public static string PositionCyrilicRegularExpression {
            get {
                return ResourceManager.GetString("PositionCyrilicRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пощенски код.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квалификация.
        /// </summary>
        public static string QualificationVM {
            get {
                return ResourceManager.GetString("QualificationVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квартал / жк.
        /// </summary>
        public static string Quarter {
            get {
                return ResourceManager.GetString("Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете {0} в диапазона от {1} до {2}.
        /// </summary>
        public static string RangeErrorMessage {
            get {
                return ResourceManager.GetString("RangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Област.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Причина.
        /// </summary>
        public static string RejectionInfo {
            get {
                return ResourceManager.GetString("RejectionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справки.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справка по чужденец.
        /// </summary>
        public static string ReportOnForeigner {
            get {
                return ResourceManager.GetString("ReportOnForeigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Генериране и извличане на справки подадени заявления по данни на чужденец.
        /// </summary>
        public static string ReportOnForeignerText {
            get {
                return ResourceManager.GetString("ReportOnForeignerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справка по статус на заявление.
        /// </summary>
        public static string ReportOnStatus {
            get {
                return ResourceManager.GetString("ReportOnStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Генериране и извличане на справки подадени заявления по статус.
        /// </summary>
        public static string ReportOnStatusText {
            get {
                return ResourceManager.GetString("ReportOnStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Генериране и извличане на справки по предварително зададени критерии.
        /// </summary>
        public static string ReportText {
            get {
                return ResourceManager.GetString("ReportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справки.
        /// </summary>
        public static string ReportTitle {
            get {
                return ResourceManager.GetString("ReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето {0} е задължително.
        /// </summary>
        public static string RequiredErrorMessage {
            get {
                return ResourceManager.GetString("RequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запис.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търсене на заявление.
        /// </summary>
        public static string SearchApplication {
            get {
                return ResourceManager.GetString("SearchApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търсене на заявления.
        /// </summary>
        public static string SearchApplicationTitle {
            get {
                return ResourceManager.GetString("SearchApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търсене на жалби.
        /// </summary>
        public static string SearchComplaint {
            get {
                return ResourceManager.GetString("SearchComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търсене на жалби.
        /// </summary>
        public static string SearchComplaintTitle {
            get {
                return ResourceManager.GetString("SearchComplaintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подадено е заявление №.
        /// </summary>
        public static string SendApplication {
            get {
                return ResourceManager.GetString("SendApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заетост от дата.
        /// </summary>
        public static string SmallDurationOfEmploymentFrom {
            get {
                return ResourceManager.GetString("SmallDurationOfEmploymentFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заетост от дата до дата.
        /// </summary>
        public static string SmallDurationOfEmploymentPeriod {
            get {
                return ResourceManager.GetString("SmallDurationOfEmploymentPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заетост до дата.
        /// </summary>
        public static string SmallDurationOfEmploymentTo {
            get {
                return ResourceManager.GetString("SmallDurationOfEmploymentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длъжност / работа.
        /// </summary>
        public static string SmallEmploymentPosition {
            get {
                return ResourceManager.GetString("SmallEmploymentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платформа за издаване на.
        /// </summary>
        public static string SmallTitle {
            get {
                return ResourceManager.GetString("SmallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код по НКПД.
        /// </summary>
        public static string SpecialityCodeVM {
            get {
                return ResourceManager.GetString("SpecialityCodeVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специалност.
        /// </summary>
        public static string SpecialityVM {
            get {
                return ResourceManager.GetString("SpecialityVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Улица / булевард / площад.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер.
        /// </summary>
        public static string StreetNo {
            get {
                return ResourceManager.GetString("StreetNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подаване на заявление за разрешение за пребиваване и работа.
        /// </summary>
        public static string SubmitApplication {
            get {
                return ResourceManager.GetString("SubmitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подаване на заявление за Краткосрочна заетост до 90 дни.
        /// </summary>
        public static string SubmitApplication90days {
            get {
                return ResourceManager.GetString("SubmitApplication90days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход в системата.
        /// </summary>
        public static string SystemLogin {
            get {
                return ResourceManager.GetString("SystemLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РАЗРЕШЕНИЯ ЗА РАБОТА.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ръководство на потребителя.
        /// </summary>
        public static string UserGuide {
            get {
                return ResourceManager.GetString("UserGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощ за потребителя.
        /// </summary>
        public static string UserHelp {
            get {
                return ResourceManager.GetString("UserHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на валидност на визата.
        /// </summary>
        public static string VisaExpirationDate {
            get {
                return ResourceManager.GetString("VisaExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер на виза.
        /// </summary>
        public static string VisaSerialNumber {
            get {
                return ResourceManager.GetString("VisaSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виза.
        /// </summary>
        public static string VisaType {
            get {
                return ResourceManager.GetString("VisaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работен плот.
        /// </summary>
        public static string WorkPlot {
            get {
                return ResourceManager.GetString("WorkPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДА.
        /// </summary>
        public static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
    }
}
